# Generated by Django 5.0.1 on 2024-01-25 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_email', '0002_alter_useremail_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='title',
        ),
        migrations.AddField(
            model_name='useremail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
