# Generated by Django 5.0.1 on 2024-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_email', '0005_alter_useremail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
